GET http://localhost:3000/movies

###
GET http://localhost:3000/movies/2

###
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Cinderella Man",
  "director": "Ron Howard",
  "year": 2008
}

###
PATCH http://localhost:3000/movies/4
Content-Type: application/json

{
  "title": "The Imitation Game",
  "director": "Morten Tyldum",
  "year": 2014
}